repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: trailing-whitespace
    - id: flake8

- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
    - id: black
