repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: trailing-whitespace

- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
    - id: black

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
    -   id: pylint

