repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
    - id: trailing-whitespace

- repo: https://github.com/doublify/pre-commit-isort
  rev: v4.3.0
  hooks:
    - id: isort

- repo: https://github.com/ambv/black
  rev: 18.5b1
  hooks:
    - id: black
