language: python

cache: pip

matrix:
  include:
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      before_install:
        - brew install python3

install:
  - make setup

script:
  - make test

deploy:
  - provider: script
    script: make deploy
    on:
      #tags: true
      all_branches: true
