language: python


cache: pip

matrix:
  include:
    - os: linux
      python: 3.6
      services: docker
    - os: osx
      language: generic
      before_install:
        - brew upgrade python
        - uname -s

install:
  - make setup

script:
  - make test

deploy:
  - provider: script
    script: make deploy
    on:
      tags: true
