language: python

python:
  - 3.6
  - 3.7

install:
  - pip install -e .[dev]
  - pip install codecov

script:
  - black --check src/
  - pylint src/
  - mypy src/
  - pytest

after_success:
  - codecov
