language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: osx
      language: generic

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then \
      brew install python python3; \
      brew link --overwrite python; fi

install:
  - make setup

script:
  - make test

deploy:
  - provider: script
    script: make deploy
    on:
      #tags: true
      all_branches: true
