language: python

python: 3.6

cache:
  directories:
    - $HOME/miniconda

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -u -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-env
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env update
  - source activate sdanalysis-dev
  - conda install -c conda-forge codecov

install:
  - pip install -e .

script:
  - pytest

after_success:
  - codecov

before_deploy:
    - conda install -n root anaconda-client conda-build
    - conda config --append channels moble
    - conda config --append channels glotzer
    - conda config --append channels malramsay
    - chmod +x scripts/deploy_anaconda.sh
    - conda config --set anaconda_upload yes
    - source activate base

deploy:
  - provider: script
    script: conda build conda_recipe --token "$CONDA_UPLOAD_TOKEN" --user "$CONDA_USER"
    on:
      tags: true
