language: generic

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/miniconda
    - $HOME/miniconda.sh

# Prepare environment for install
before_install:
  - if [[ $(uname -s) == "Darwin" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -u -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-env
  # Useful for debugging any issues with conda
  - conda info -a

  # Install dependencies from environment.yml file
  - conda env update
  - pip install codecov

install:
  - source activate sdanalysis-dev
  - python setup.py install --single-version-externally-managed --record record.txt

before_cache:
  # Uninstall sdanalysis package
  - tr '\n' '\0' < record.txt | xargs -0 sudo rm -f --
  - conda clean --all
  - rm ~/miniconda/conda-meta/history
  - rm -r ~/miniconda/lib/python3.6/__pycache__

script:
  - pytest

after_success:
  - codecov

before_deploy:
  - conda install -n root anaconda-client conda-build
  - conda config --append channels moble
  - chmod +x scripts/deploy_anaconda.sh

deploy:
  - provider: script
    script: ./scripts/deploy_anaconda.sh
    #on:
      #tags: true
  - provider: pypi
    user: "$PYPI_UNAME"
    password: "$PYPI_PASSWORD"
    #on:
      #tags: true
