language: generic

os:
  - linux
  - osx

cache:
  directories:
    - "$HOME/miniconda"
    - "$HOME/download"

install:
  - make setup

before_cache:
  - tr '\n' '\0' < record.txt | xargs -0 sudo rm -f --
  - conda clean --all
  - rm ~/miniconda/conda-meta/history
  - rm ~/miniconda/envs/sdanalysis-dev/conda-meta/history
  - rm -r ~/miniconda/lib/python3.6/__pycache__

script:
  - make test

before_deploy:
  - echo -e "[pypi]\nusername = $TWINE_USERNAME=\npassword=$TWINE_PASSWORD" > ~/.pypirc

deploy:
  - provider: script
    script: make deploy
    on:
      #tags: true
      all_branches: true
