package:
    name: statdyn
    version: {{ GIT_DESCRIBE_TAG }}

about:
    home: https://github.com/malramsay64/MD-Molecules-Hoomd
    license: MIT
    license_file: LICENSE

source:
    path: .
    #git_url: https://github.com/malramsay64/MD-Molecules-Hoomd.git

requirements:
    build:
        - python 3.6.1
        - setuptools 36.*
        - setuptools_scm 1.15*
        - cython 0.26.*
        - voro
        - numpy 1.13.1

    run:
        - python 3.6.1
        - numpy 1.13.1
        - scipy 0.19.0
        - scikit-learn 0.19.0
        - pandas 0.20.3
        - pytables 3.4*
        - bokeh 0.12.9
        - setuptools *
        - freud 0.6.*
        - gsd 1.2.0*
        - cython 0.26.*
        - keras
        - scikit-learn

build:
    entry_points:
        - sdrun = statdyn.sdrun.main:sdrun
    preserve_egg_dir: True
    script: python setup.py install
    number: {{ GIT_DESCRIBE_NUMBER }}

test:
    requires:
        - pytest
        - hypothesis
        - quaternion
    source_files:
        - test/*
    commands:
        - python -c "import statdyn"
        - pytest -v -c test/test_setup.cfg
