package:
    name: sdanalysis
    version: {{ GIT_DESCRIBE_TAG }}

about:
    home: https://github.com/malramsay64/statdyn-analysis
    license: MIT
    license_file: LICENSE

source:
    git_url: https://github.com/malramsay64/statdyn-analysis

requirements:
    build:
        - python 3.6.3
        - setuptools 36.5.0
        - setuptools_scm 1.15.6
        - cython 0.27.3
        - voro 0.4.6
        - numpy 1.13.3

    run:
        - python 3.6.3
        - numpy 1.13.3
        - scipy 1.0.0
        - scikit-learn 0.19.0
        - pandas 0.21.0
        - pytables 3.4.2
        - bokeh 0.12.11
        - setuptools 36.5.0
        - freud 0.6.2
        - gsd 1.4.0
        - cython 0.27.3

build:
    entry_points:
        - sdanalysis = sdanalysis.main:sdanalysis
    preserve_egg_dir: True
    script: python setup.py install
    number: {{ GIT_DESCRIBE_NUMBER }}

test:
    import:
        - sdanalysis
    requires:
        - pytest 3.3.0
        - hypothesis 3.38.5
        - quaternion
    source_files:
        - test/*
    commands:
        - pytest -v
