{% set version = "0.5.5" %}

package:
  name: sdanalysis
  version: {{ version }}

about:
  home: https://github.com/malramsay64/statdyn-analysis
  license: MIT
  license_file: LICENSE
  summary:  Collection of tools for the statistical dynamics analysis of Molecular Dynamics trajectories.


source:
  git_url: https://github.com/malramsay64/statdyn-analysis
  git_rev: v{{ version }}


requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools
    - cython >=0.27.3


  run:
    - {{ pin_compatible('python', max_pin='x.x') }}
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - scipy >=1.0
    - scikit-learn ==0.19.0
    - pandas >=0.21
    - pytables >=3.4
    - bokeh >=0.12.11
    - setuptools
    - gsd >=1.3.0
    - pyyaml
    - hsluv
    - attrs
    - click

build:
  entry_points:
    - sdanalysis = sdanalysis.main:sdanalysis
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 1
  include_recipe: False

test:
  import:
    - sdanalysis
  requires:
    - pytest
    - hypothesis
    - quaternion = 2018.02*
    - pytest-lazy-fixture
  source_files:
    - test/
  commands:
    - pytest -v
