{% set version = "0.9.0" %}

package:
  name: sdanalysis
  version: {{ version }}

about:
  home: https://github.com/malramsay64/statdyn-analysis
  license: MIT
  license_file: ../LICENSE
  summary:  Collection of tools for the statistical dynamics analysis of Molecular Dynamics trajectories.


source:
  git_url: https://github.com/malramsay64/statdyn-analysis
  git_rev: v{{ version }}


requirements:
  host:
    - python {{ python }}
    - setuptools
    - pip


  run:
    - {{ pin_compatible('python', max_pin='x.x') }}
    - numpy =1.16.*
    - scipy >=1.0
    - scikit-learn >=0.20.0
    - pandas >=0.21
    - pytables >=3.5.1
    - bokeh ==1.*
    - gsd >=1.3.0
    - pyyaml >=5.1
    - hsluv
    - attrs
    - click ==7.*
    - freud ==1.0.*
    - rowan
    - tqdm
    - joblib

build:
  noarch: python
  entry_points:
    - sdanalysis = sdanalysis.main:sdanalysis
  script: python -m pip install --no-deps .
  number: 0

test:
  import:
    - sdanalysis
  requires:
    - pytest
    - hypothesis
    - pytest-lazy-fixture
  source_files:
    - test/
  commands:
    - python -m pytest
